.gitignore
packer-rocm/README.md
packer-rocm/playbooks/build.yml
packer-rocm/playbooks/rocm.yml
packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl
packer-rocm/ubuntu/ubuntu-rocm.variables.pkr.hcl

Realizing I overdid it a bit, assuming both `amdgpu-dkms` and `rocm` will want to be installed. The packages included in the image is now configurable with `amdgpu_install`.
One may now opt to build an image only with `amdgpu-dkms`, just `amdgpu-install`, or as many extra packages are desired.
Up next: `ga` _(or equivalent)_; if `repo.radeon.com` is used or Artifactory/another URL for `amdgpu-install`

packer-rocm: configurable packages w/ 'amdgpu_install'

---

redfish-exporter/main.go
redfish-exporter/redfish_utils.go

Added fault tolerance when the server already has a subscription with conflicting Destination field.
The check happens before sending and not as response to an error, as the the responses from the BMC seem to vary between version/manufacturers, making parsing it trickier.

Fault tolerance with conflicting destinations

---

redfish-exporter/README.md
redfish-exporter/integration_test.sh
redfish-exporter/listener.go
redfish-exporter/metrics/metrics.go
redfish-exporter/slurm/queue.go
redfish-exporter/slurm/slurm.go

And this is the output from `/metrics`:
```
SlurmAPI_success{EventAction="DrainNode",EventMessageId="IDRAC.2.9.CPU0001",SlurmNodeName="computenode1",SourceIP="https://10.30.64.17"} 2
SlurmAPI_failure{EventAction="DrainNode",EventMessageId="IDRAC.2.9.CPU0001",SlurmNodeName="computenode1",SourceIP="https://10.30.64.17"} 1
```

Add slurm API call counters to prometheus

---

packer-rocm/playbooks/rocm.yml

Extend the set of common package requirements among Debian/RedHat families

packer-rocm: extend common package list

---

packer-rocm/playbooks/roles/tuned_profile/README.md
packer-rocm/playbooks/roles/tuned_profile/defaults/main.yml
packer-rocm/playbooks/roles/tuned_profile/files/acs_disable.sh
packer-rocm/playbooks/roles/tuned_profile/files/tuned.fact
packer-rocm/playbooks/roles/tuned_profile/handlers/main.yml
packer-rocm/playbooks/roles/tuned_profile/meta/argument_specs.yml
packer-rocm/playbooks/roles/tuned_profile/tasks/main.yml
packer-rocm/playbooks/roles/tuned_profile/templates/tuned_profile.j2
packer-rocm/playbooks/tuned.yml
packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl

Porting over our `tuned_profile` role and some common parameters

packer-rocm/tuned_profile: init

---

packer-rocm/README.md
packer-rocm/packages/README.md
packer-rocm/playbooks/package-globber.yml
packer-rocm/playbooks/rocm.yml
packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl

For packages not available in a repository or generally over the internet, a `packages` directory has been introduced. Any `.rpm` or `.deb` files placed here will be installed as part of image creation!

packer-rocm: introduce `packages` dir

---

packer-rocm/playbooks/os_prep.yml
packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl

Certain packages on certain distributions provide `udev` rules that assume RDMA devices should have the `NAME_FALLBACK` mode:
> NAME_FALLBACK - Try to name devices in the following order:
>                by->onboard -> by-pci -> by-guid -> kernel
reference: https://github.com/linux-rdma/rdma-core/blob/master/kernel-boot/rdma_rename.c#L22
This play defaults to `NAME_KERNEL` instead:
> NAME_KERNEL - leave name as kernel provided
Why? Determinism. The kernel is a property chosen _(determined)_ as part of the deployment, and consequently, the name.
The playbook accepts variables, but these are not exposed to Packer. May be used elsewhere

packer-rocm/os+udev: set 'NAME_KERNEL' RDMA rename mode

---

packer-rocm/playbooks/build.yml
packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl
packer-rocm/ubuntu/ubuntu-rocm.variables.pkr.hcl
packer-rocm/ubuntu/user-data-rocm

Found that `cloud-init` has trouble extending LVM to fill storage, see below. Instead of working around this... fall back to partitions.
Secondarily: parameters controlling resources for the builder have been added.
```
/var/log/cloud-init.log:2024-10-11 22:10:06,904 - cc_growpart.py[DEBUG]: '/' SKIPPED: Resizing mapped device (/dev/mapper/ubuntu--vg-ubuntu--lv) skipped as it is not encrypted.
```

packer-rocm/disk/vars: drop LVM, 'cloud-init' limitation. add vars

---

redfish-exporter/.env
redfish-exporter/config.go
redfish-exporter/grafana_dashboard.json
redfish-exporter/k8s/exporter-configmap.yaml
redfish-exporter/main.go

Add a Grafana dashboard JSON template to visualize the data.
Add Prometheus initializer:
- Add default labels to init counters
- Match host label with received IP from event
Resolve an issue with Prometheus counters not being initialized (By Prometheus design) thus the first event is always being ignored:
https://github.com/prometheus/prometheus/issues/1673

Add Grafana dashboard

---

.gitmodules
packer-rocm/README.md
packer-rocm/playbooks/build.yml
packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl
packer-rocm/ubuntu/ubuntu-rocm.variables.pkr.hcl
packer-rocm/ubuntu/user-data-rocm
redfish-exporter/.env
redfish-exporter/README.md
redfish-exporter/config.go
redfish-exporter/docs/configuration.md
redfish-exporter/grafana_dashboard.json
redfish-exporter/k8s/exporter-configmap.yaml
redfish-exporter/main.go
redfish-exporter/slurm/slurm.go
slurm/README.md

In #35 I aimed to drop LVM, return to plain disk images. This was mistaken. MaaS cannot find `/curtin` within. Images produced currently are unfit for purpose.
This _appears_ to be due to _partially_ following in the footsteps of `packer-maas`. The storage layout goes from `lvm` to `direct`, but I missed their post-processing.
With non-LVM images we can't just compress the image, apparently. MaaS wants those repacked as a tarball.
`packer-maas` 'flat' references:
- [user-data](https://github.com/canonical/packer-maas/blob/main/ubuntu/user-data-flat)
- [Packer HCL](https://github.com/canonical/packer-maas/blob/main/ubuntu/ubuntu-flat.pkr.hcl)
Context/differentiation, the LVM references:
- [user-data](https://github.com/canonical/packer-maas/blob/main/ubuntu/user-data-lvm)
- [Packer …

packer-rocm/LVM-dropfix: add post-processor for 'flat'/tarball creation

---

packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl

More fixes following the LVM -> direct partition, 'raw image' -> tarball adjustments.
The partition index was wrong, I misunderstood the usage - changed it when the problem lied elsewhere _(missing some NBD/fuse dependencies)_. This undoes that, allowing the root partition to finally be found.
Upstream uses `gzip`, we can speed this up with `pigz` and an exported function _(aliases don't work for sourced files)_

packer-rocm/post-processor: fixes

---

redfish-exporter/LICENSES/third_party/NOTICE
redfish-exporter/LICENSES/third_party/github.com/beorn7/perks/quantile/LICENSE
redfish-exporter/LICENSES/third_party/github.com/cespare/xxhash/v2/LICENSE.txt
redfish-exporter/LICENSES/third_party/github.com/joho/godotenv/LICENCE
redfish-exporter/LICENSES/third_party/github.com/klauspost/compress/LICENSE
redfish-exporter/LICENSES/third_party/github.com/klauspost/compress/internal/snapref/LICENSE
redfish-exporter/LICENSES/third_party/github.com/klauspost/compress/zstd/internal/xxhash/LICENSE.txt
redfish-exporter/LICENSES/third_party/github.com/munnerz/goautoneg/LICENSE
redfish-exporter/LICENSES/third_party/github.com/prometheus/client_golang/internal/github.com/golang/gddo/httputil/LICENSE
redfish-exporter/LICENSES/third_party/github.com/prometheus/client_golang/prometheus/LICENSE
redfish-exporter/LICENSES/third_party/github.com/prometheus/client_golang/prometheus/NOTICE
redfish-exporter/LICENSES/third_party/github.com/prometheus/client_model/go/LICENSE
redfish-exporter/LICENSES/third_party/github.com/prometheus/client_model/go/NOTICE
redfish-exporter/LICENSES/third_party/github.com/prometheus/common/LICENSE
redfish-exporter/LICENSES/third_party/github.com/prometheus/common/NOTICE
redfish-exporter/LICENSES/third_party/github.com/prometheus/procfs/LICENSE
redfish-exporter/LICENSES/third_party/github.com/prometheus/procfs/NOTICE
redfish-exporter/LICENSES/third_party/github.com/stmcginnis/gofish/LICENSE
redfish-exporter/LICENSES/third_party/golang.org/x/sys/unix/LICENSE
redfish-exporter/LICENSES/third_party/google.golang.org/protobuf/LICENSE

- Include copyright notice and license text as required
- Any additional libraries should be added by running: `go-licenses save . --save_path="./LICENSES/third_party"` from the redfish-exporter

Add licenses for third-party libraries

---

packer-rocm/playbooks/niccli.yml
packer-rocm/playbooks/roles/niccli/defaults/main.yml
packer-rocm/playbooks/roles/niccli/tasks/main.yml

The 230 release has been with us for a while, inspired by attempts to use a newer kernel... I'm looking to update `niccli`.

packer-rocm/niccli: update to 231.2.63.0a

---

packer-rocm/README.md
packer-rocm/playbooks/build.yml
packer-rocm/playbooks/rocm.yml
packer-rocm/playbooks/roles/niccli/tasks/main.yml
packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl
packer-rocm/ubuntu/ubuntu-rocm.variables.pkr.hcl

The kernel requests have so far been ignored. The image lands with latest `linux-generic`, despite the fully-automated path preferring `linux-hwe`.
To handle this, adopt the `install--custom-kernel.sh` script from `packer-maas` and pass the variable along. The script will exit if unset.
Testing underway

packer-rocm/custom kernel: forward request, use script

---

packer-rocm/README.md
packer-rocm/playbooks/build.yml
packer-rocm/ubuntu/ubuntu-rocm.variables.pkr.hcl

Now that both sides of the coin have been tested - `5.15` and `6.8` _(#47)_  - defaulting to the newer release, showing users how to go back if desired.
As-is, images are produced with two kernels. The newer HWE one as requested, but also the generic release as well. Many options exist 😄
After this PR: I can/will remove at least one point of repetition with the defaults - `build.yml` with improved templating can defer to Packer _(`ubuntu-rocm.variables.pkr.hcl`)_

packer-rocm/defaults: drop 5.15 specifier for HWE kernel, use 6.8

---

packer-rocm/playbooks/build.yml

For maintainability it's not ideal to repeat the Packer variables _(or their values)_ in the `build.yml` playbook. Should construct the `packer build` command and variable awareness dynamically.

packer-rocm/maintainability: rm var dupes

---

packer-rocm/playbooks/build.yml

Too-tightly bound the variable discovery. It finds those for the custom image here, not those included with `packer-maas`.

packer-rocm/README: include (upstream) 'headless' var in construction

---

.gitignore
.gitmodules
packer-rocm/README.md
packer-rocm/playbooks/build.yml
packer-rocm/requirements.yml
packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl
packer-rocm/ubuntu/ubuntu-rocm.variables.pkr.hcl

Instead of having the user figure out how to get a laundry list of prerequisites, try to handle them _(on Linux, for RedHat and Debian families)_

packer-rocm: auto prereqs

---

packer-rocm/README.md
packer-rocm/playbooks/build.yml

Ergonomics for submodules are a bit unusual, note the recursion option. Also: relax the copies in `build.yml`

packer-rocm/submodule: +arg for clone, sync excludes++

---

.github/workflows/packer-rocm.yaml
packer-rocm/README.md
packer-rocm/playbooks/build.yml
packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl
packer-rocm/ubuntu/ubuntu-rocm.variables.pkr.hcl

Want to keep the Ansible bits in good shape, adding `ansible-lint`.
Some preparations for `packer validate` as well... but that has challenges. The files need assembled 'just so' first, as if building.

packer-rocm/actions: introduce 'ansible-lint', 'headless'->'hidden'

---

packer-rocm/README.md
packer-rocm/playbooks/build.yml

- fix: demonstrate `rocm_installed=true` usage in `README` 
- _[originally]_ showed many releases in the request... but _ROCm_ is not installed by default, only the `amdgpu` driver.
- without `rocm_installed=true`, only the highest release is used _[for the driver]._
- fix: use `packer_dist` when setting the `packer build` working directory
- QoL: show image file name in `packer build` task

packer-rocm: minor fixes

---

packer-rocm/README.md
packer-rocm/ubuntu/ubuntu-rocm.variables.pkr.hcl

If using a non-HWE kernel, the included packages seem incomplete. The `bnxt_re` driver didn't load until after `extra-modules` were installed... which provides `uverbs` as a module. This prevented `amdgpu` from loading.
Note the importance of the package in the README without so much detail, include a placeholder/reminder in the vars.

packer-rocm/README+vars: note 'extras' w/ non-HWE, +placeholder

---

packer-rocm/README.md
packer-rocm/playbooks/build.yml
packer-rocm/playbooks/os_prep.yml
packer-rocm/playbooks/rocm.yml
packer-rocm/repositories/README.md
packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl
packer-rocm/ubuntu/ubuntu-rocm.variables.pkr.hcl

It may be preferable to add more repositories to the image. Not just for certain `amdgpu` or `ROCm` releases... but any software at all.
To that end, introduce the `repositories` directory. Any `.repo` or `.list` files that apply for the given OS family will be copied to the builder VM. Example:
```
deb [ trusted=yes ] http://artifactory.domain.tld/artifactory/list/repository-name/ jammy/6.3 amdgpu-pro
```
For the specific `amdgpu`/ROCm use-case, the `rocm_repos` variable has been introduced. This may be used to opt out of the GA repositories at `repo.radeon.com`.

packer-rocm/repos: +dir for overrides, bool for GA-optout

---

packer-rocm/playbooks/build.yml
packer-rocm/playbooks/roles/amdgpu_install/vars/main.yml

Doing some piecemeal testing, found a potential gap with dependencies - `libyaml` _(are many, a C++ variant)_

packer-rocm/amdgpu_install/vars: package changes

---

packer-rocm/requirements.yml

Resolves:
```
(item={'name': 'bnxt_en'}) => {"ansible_loop_var": "module", "changed": false, "module": {"name": "bnxt_en"}, "msg": "Unsupported parameters for (community.general.modprobe) module: persistent. Supported parameters include: name, params, state."}
```
... something one may find with some (outdated) _ansible-full_ installations

packer-rocm: specify exact release for community.general

---

packer-rocm/playbooks/os_prep.yml

This set of Packer-specific tasks make the playbook not particularly friendly when run natively, insisting the input of _'repository overrides'_ exist.
Assume the repositories given to `packer-rocm` _should_ be synchronized with the managed host... but allow it to be opted-out. Also, tag the tasks.
This makes `os_prep.yml` generally much more useful when _not_ building an image. For instance: `cloud-init`+`ansible-pull` while building a live system, no Packer involved.

packer-rocm/os-prep: block reposync tasks, allow non-packer runs

---

packer-rocm/playbooks/niccli.yml
packer-rocm/playbooks/roles/niccli/defaults/main.yml

This change addresses a precedence problem with Ansible. Setting both `niccli_url` and `niccli_sum` immediately under the `role` may take precedence over `-e` _(extra-vars)_ on the command-line.
The role defaults are generally sufficient, there is little need for this. Remove the problematic statements and bump the default release.

niccli role: use defaults, don't set in play

---

packer-rocm/playbooks/amdgpu_install.yml
packer-rocm/playbooks/niccli.yml
packer-rocm/playbooks/os_prep.yml
packer-rocm/playbooks/package-globber.yml
packer-rocm/playbooks/tuned.yml

As part of the image building with Packer, Ansible was being told to expect hosts in the `default` group in the inventory. This placed an arbitrary restriction on users; hosts hoping to benefit from these Playbooks also had to be placed in that group.
This changes the applicable host spec to `all`; opening the playbook to _any_ inventory hosts. The `--limit` argument may be used to limit scope _(either host or group names are accepted)_

packer-rocm/external: set 'all' hostspec, suggest '--limit'

---

smci_mi300x_platform_amdgpu_alllogs_collection.sh

Minor changes to smci_mi300x_platform_amdgpu_alllogs_collection.sh.  Verbosity reduced and removing the logs folder, instead putting the output file directly in to the folder the script runs within.

Verbosity of smci_mi300x_platform_amdgpu_alllogs_collection.sh reduced.

---

packer-rocm/playbooks/build.yml
packer-rocm/playbooks/limits.yml
packer-rocm/playbooks/roles/gpu_perf_config/files/10-sre-limits.conf
packer-rocm/playbooks/roles/gpu_perf_config/tasks/main.yml
packer-rocm/playbooks/roles/sos/README.md
packer-rocm/playbooks/roles/sos/defaults/main.yml
packer-rocm/playbooks/roles/sos/tasks/main.yml
packer-rocm/playbooks/sos.yml
packer-rocm/ubuntu/ubuntu-rocm.pkr.hcl
packer-rocm/ubuntu/user-data-rocm

- Cleanliness/hardening: `ubuntu` user becomes `packer`, is now removed as part of `shutdown_command`
- Remove `custom-packages.tar.gz` before creation, avoid conflict/growing collection between builds.
- Run `packer init ...` on the workspace before build, ensuring plugins are installed
- Introduced two roles:
- `gpu_perf_config`: simple drop-in config for `/etc/security/limits.d`
- `sos`: prepares [sos](https://github.com/sosreport/sos), [xsos](https://github.com/ryran/xsos), and commands to include with reports.

Packer: Hardening, Resource limits, Debug

---

.github/workflows/packer-rocm.yaml

Updating the `packer-maas` submodule for `packer-maas`, largely for [this commit](https://github.com/canonical/packer-maas/commit/046b0986c630e71b772c6581d39c72ae89a00647).
Resolves: may find the Apt caches have gone stale when using the `custom-packages` facility

packer-{rocm,maas}: improve "custom-packages" longevity, bump submodule
